[versions]
compileSdk = "33"
minSdk = "28"
targetSdk = "33"
appVersion = "1.0.0"
versionCode = "10000"

# kotlin
kotlin = "1.8.21"
kotlinx-serialization-json = "1.5.1"
kotlinx-serialization-converter = "1.0.0"
kotlinx-coroutines = "1.7.1"
kotlinx-datetime = "0.4.0"

# android
corektx = "1.10.1"
appcompat = "1.6.1"
activity = "1.7.2"
lifecycle = "2.6.1"
navigation = "2.6.0"
startup = "1.1.1"
security = "1.1.0-alpha06"
compose-compiler = "1.4.7"
compose-bom = "2023.05.01"
desugarJdk = "2.0.3"
dagger-hilt = "2.46.1"
dagger-hilt-navigation-compose = "1.0.0"

# material + google
material = "1.9.0"
accompanist = "0.30.1"
in-app-update = "2.1.0"
secret-gradle-plugin = "2.0.1"
google-services = "4.3.15"
crashlytics = "2.9.6"
firebase = "32.1.1"

# test
junit = "4.13.2"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"
junit5-plugin = "1.9.3.0"
junit5-jupiter = "5.9.3"
truth = "1.1.5"
robolectric = "4.10.3"
androidx-uiautomator = "2.3.0-alpha03"
androidx-test = "1.5.2"

# gradle
agp = "8.0.2"
kspplugin = "1.8.21-1.0.11"

# third party
flipper = "0.201.0"
soloader = "0.10.5"
okhttp = "4.11.0"
retrofit = "2.9.0"
timber = "5.0.1"
coil = "2.4.0"
lottie = "6.0.1"
ktlint = "11.4.0"
sentry = "3.11.1"
sentry-android = "6.23.0"
process-pheonix = "2.1.2"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "corektx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]

