name: Pophory PR Builder

on:
  pull_request:
    branches: [ develop, master ]

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Add Local Properties
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
          POPHORY_BASE_URL: ${{ secrets.POPHORY_BASE_URL }}
          KEY_ALIAS: ${{ secrets.SENTRY_DSN }}
          KEY_PASSWORD: ${{ secrets.SENTRY_DSN }}
          STORE_PASSWORD: ${{ secrets.SENTRY_DSN }}
          AMPLITUDE_KEY: ${{ secrets.SENTRY_DSN }}
        run: |
          echo sentryDsn=\"$SENTRY_DSN\" >> ./local.properties
          echo kakaoApiKey=$KAKAO_API_KEY >> ./local.properties
          echo pophoryBaseUrl=$POPHORY_BASE_URL >> ./local.properties
          echo keyAlias=$KEY_ALIAS >> ./local.properties
          echo keyPassword=KEY_PASSWORD >> ./local.properties
          echo storePassword=$STORE_PASSWORD >> ./local.properties
          echo amplitudeKey=$AMPLITUDE_KEY >> ./local.properties

      - name: Access Firebase Service
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: On Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#53A551'
          SLACK_ICON: https://github.com/TeamPophory/pophory-android/assets/54518925/c37e7b33-066a-4d53-8c9d-bc96ec8c7829?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'ALL Pophory Android Makers checks have passed ✅🫡'
          MSG_MINIMAL: true
          SLACK_USERNAME: Pophory Android
          SLACK_MESSAGE: 'Pophory Android PR check 성공 🎉🎉🎉'

      - name: On Failed, Notify in Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_ICON: https://github.com/TeamPophory/pophory-android/assets/54518925/c37e7b33-066a-4d53-8c9d-bc96ec8c7829?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'Pophory checks have failed ⚠️🚫'
          MSG_MINIMAL: true
          SLACK_USERNAME: Pophory Android
          SLACK_MESSAGE: '버그 저리가'
